### ISSUE TITLE
Provide greater flexibility in command-line configurations

### ISSUE THREAD

**Issue by nsaechao** [standard/standard-engine#169]
standard-engine feels great when configured for one project. I would like to integrate standard-engine as a baseline configuration for many projects. I am running into issues with being able to configure simple things like cwd, ignorePath, etc... on the fly (i.e. command-line parameters).

One area that can be improved would be the customizable parseOpts function by allowing non-standard flags to be passed in. Currently argv._ assumes all inputs are files, it would be nice if there is a way to parse out custom parameters that can be used in the parseOpts method.

Please let me know your thoughts, I would be willing to contribute.

**Comment by feross** [comment]
Hey @nsaechao, it sounds like you're using the `standard-engine` Node.js API. So that means that you're responsible for whatever arguments you pass into the `lintFiles()` and related functions. If you want to detect additional command line flags, like for example `--myFlag`, you can just do that in your own command line argument parsing code, unless I'm missing something.
